# Generated by go2rpm 1
%bcond_without check

# https://github.com/couchbase/ghistogram
%global goipath         github.com/couchbase/ghistogram
Version:                0.0.0
%global commit          d910dd063dd68fb4d2a1ba344440f834ebb4ef62

%gometa

%global common_description %{expand:
Simple int histogram for golang.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Simple int histogram for golang

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Jan 26 04:39:29 CET 2020 Marcel Metz <mmetz@adrian-broher.net> - 0.0.0-1.20200126gitd910dd0
- Initial package
